root: true
extends:
  - eslint:recommended
  - react-app
  - react-app/jest
settings:
  import/resolver:
    typescript:
      project: ./src
rules:
  import/order:
    - error
    - alphabetize:
        order: asc
        caseInsensitive: true
      groups:
        - builtin
        - external
        - internal
        - [parent, sibling]
        - index
      newlines-between: always
